name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - run: |
        cargo clippy --all-targets --all-features -- -D warnings
        cargo test --verbose
        cargo doc --verbose
