name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - run: cargo fmt -- --check
    - run: cargo clippy -- -D warnings
    - run: cargo test --verbose
    - run: cargo doc --verbose
